application: passtiche
version: 0-11
runtime: python27
api_version: 1
threadsafe: true


handlers:
    
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /js
  static_files: static/js/badge/badge.js
  upload: static/js/badge/badge.js

- url: /badge
  static_files: static/images/Add_to_Passbook_Badge_2x.png
  upload: /static/images/Add_to_Passbook_Badge_2x.png


- url: /demo.pkpass
  static_files: static/passes/Apple/Coupon.pkpass
  upload: /static/passes/Apple/Coupon.pkpass

- url: /coupon.pkpass
  static_files: static/passes/Apple/Coupon.pkpass
  upload: /static/passes/Apple/Coupon.pkpass  

- url: /event.pkpass
  static_files: static/passes/Apple/Event.pkpass
  upload: /static/passes/Apple/Event.pkpass  

- url: /generic.pkpass
  static_files: static/passes/Apple/Generic.pkpass
  upload: /static/passes/Apple/Generic.pkpass  

- url: /storecard.pkpass
  static_files: static/passes/Apple/StoreCard.pkpass
  upload: /static/passes/Apple/StoreCard.pkpass  


- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html




- url: /pf/
  static_dir: static/passes
  mime_type: application/vnd.apple.pkpass

- url: /static/
  static_dir: static


### CONSOLE ###

- url: /console/static
  static_dir: console/app/view/static  
  
- url: /console.*
  script: console.app.console.app
  login: admin
  

- url: /cron/.*
  script: main.application
  login: admin

- url: /admin/.*
  script: main.application
  login: admin  
    
# TESTING

- url: /test.*
  login: admin  # This is important if you deploy the test directory in production!
  script: utils.gaeunit.app

# MAIN VIEWS

- url: /.*
  script: main.application
  
  

builtins:
  - remote_api: on
  - default: on
  - appstats: on
  - deferred: on 

inbound_services:
  - xmpp_message
  - mail
  - channel_presence

