application: passtiche
version: 0-05
runtime: python
api_version: 1


handlers:
    
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html


   

- url: /pf/
  static_dir: static/passes
  mime_type: application/vnd.apple.pkpass

- url: /static/
  static_dir: static


### CONSOLE ###

- url: /console/static
  static_dir: console/app/view/static  
  
- url: /console.*
  script: console/app/console.py
  login: admin
  
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /cron/.*
  script: main.py
  login: admin

- url: /admin/.*
  script: main.py
  login: admin  
    

- url: /.*
  script: main.py 
  
  

builtins:
  - remote_api: on
  - datastore_admin: on
  - appstats: on
  - deferred: on 

inbound_services:
  - xmpp_message
  - mail
  - channel_presence

